### ISSUE TITLE
The schematics show for v3 a BME280 Yet this is not found 

### ISSUE THREAD

**Issue by parahooners** [LilyGO/LILYGO-T-Energy#10]
The schematics show for v3 a BME280 Yet this is not found 

Could not find a valid BME280 sensor, check wiring, address, sensor ID!
SensorID was: 0xFF
        ID of 0xFF probably means a bad address, a BMP 180 or BMP 085
   ID of 0x56-0x58 represents a BMP 280,
        ID of 0x60 represents a BME 280.
        ID of 0x61 represents a BME 680.

Considering the capabilities of this board - the docs suck

**Comment by hanswurst1337** [comment]
The BME280 IC is not included. There is a place on the PCB next to the micro USB jack, so you can solder one in.
